### PR TITLE
Fix compilation with JDK 11.

### PR DESCRIPTION
**Pull request by hlinnaka**
We were using a few deprecated functions, which caused warnings, which
were turned into errors thanks to -Werror.

### CODE REVIEW

**Comment by hlinnaka** [comment]
> This looks good. I tested it with both JDK 8 and 11. However, unit tests still need to be fixed for 11.

Ah, ok. The README says the unittests can be run with `make unittest`, but that doesn't work
```
make: *** No rule to make target 'unittest'.  Stop.
```
I presume the README is wrong, and the correct way to run the unit tests is `make test`?

**Comment by frankgh** [comment]
> ```
> make: *** No rule to make target 'unittest'.  Stop.
> ```
> 
> I presume the README is wrong, and the correct way to run the unit tests is `make test`?

yes, you are correct. README is wrong. It should be `make test`

**Comment by frankgh** [comment]
@hlinnaka feel free to merge this when conflicts are resolved

**Comment by hlinnaka** [comment]
> @hlinnaka feel free to merge this when conflicts are resolved

Rebased and included a paragraph in the commit message about the regression test failures. I left out the README change for now, since you still need JDK 8 to run the regression tests.

I don't think I have push access to this repository, though. Would you mind merging this for me?

**Comment by frankgh** [comment]
Thanks for your contribution! Merging now

**Pull request merged**
