### PR TITLE
Downgrade to Spring Boot 2.4.3

### PR DESCRIPTION
**Pull request by bradfordb-vmware**
Downgrading Spring Boot in order to downgrade from Apache Tomcat 9.0.48 to 9.0.43. We have observed that in certain scenarios, some responses from PXF to GPDB that do not have any data fail to include a zero-length chunk (i.e., `0\r\n\r\n`). The PXF extension which uses curl to make HTTP requests against the PXF server will report a "partial file transfer" error.

Testing shows that this error is not seen when using Apache Tomcat 9.0.43.

### CODE REVIEW

**Review by denalex — APPROVED** [review]
Can we please have the short description in the PR summary of a problem we faced with the newer Boot/Tomcat that caused this PR.

**Comment by BeibitKZ** [comment]
Hi team! After Upgrading PXF from version 6.3.1 to 6.4.2 and SpringBoot to 2.5.12, the "Transferred a partial file" error ocucured again. Is it possble to solve it without SptingBoot downgrade?

**Comment by denalex** [comment]
We can not reproduce this issue in our environments. @BeibitKZ - if you have a reliable reproduction or description of workload that causes the issue, please let us know so that we can get to the root cause.

**Comment by BeibitKZ** [comment]
Hi Alex! Sure, here is part of log from GP cluster:

[clgp1-0008] /data1/primary/gpseg131/pg_log/gpdb-2023-01-06_000000.csv:460509:2023-01-06 11:59:18.489773 ALMT,"u_utsklgrnplm_s_as_t_didsd_ppl","uat",p3234647,th-745805696,"192.168.60.226","65348",2023-01-06 11:59:13 ALMT,65108506,con88423,cmd40,seg131,,dx90434,x65108506,sx1,"LOG","00000","duration: 14.076 ms",,,,,,"INSERT INTO S_GRNPLM_AS_T_DIDSD_083_DB_STG.ETL_BKALOG083900001 (SQL_QUERY,RUN_TM,PARAM,PROC) VALUES ( 'ErrorState:=XX000 ErrorCODE:=XX000 ERRORTEXT:=transfer error (18): Transferred a partial file from ''127.0.0.1:5888'' (libchurl.c:929)  (seg337 slice1 192.168.60.243:10017 pid=1588119)', clock_timestamp(), 'FAILLmain.wf=14301436', 'sp_load_a_table_900001_contr_status');",0,,"postgres.c",1438,
[clgp1-0008] /data1/primary/gpseg131/pg_log/gpdb-2023-01-07_103306.csv:519260:	AND error_msg LIKE '%Transferred a partial file%'

PXF 6.4.2
SpringBoot 2.5.12

**Comment by RekGRpth** [comment]
I was finally able to achieve stable reproduction of the error on the demo cluster!
```sql
create extension pxf;
create table a(a int, b int, c int) DISTRIBUTED BY (a);
insert into a select 0, i, i from generate_series(1, 10001) i;
insert into a select 2, i, i from generate_series(1, 20) i;
insert into a select -1, i, i from generate_series(1, 30) i;
analyze a;
create function sleep(a int) returns bool language plpgsql as $function$ declare
begin
    if a > 10000 then
        return 1 / 0 is null;
    end if;
    return true;
end;$function$;
create view b as select gp_segment_id as a, b, c from a where sleep(b);
CREATE EXTERNAL TABLE c(a int, b int, c int)
LOCATION('pxf://postgres.b?PROFILE=JDBC&JDBC_DRIVER=org.postgresql.Driver&DB_URL=jdbc:postgresql://localhost:6432/postgres')
FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');

--set client_min_messages = debug3;
set log_min_messages = debug3;

SELECT a, count(*) FROM c group by 1;

ERROR:  transfer error (18): Transferred a partial file from '127.0.0.1:5888' (libchurl.c:924)  (seg0 slice1 172.19.0.4:6434 pid=128244) (libchurl.c:924)
DETAIL:  curl error buffer: transfer closed with outstanding read data remaining
CONTEXT:  External table c
```

**Comment by ashuka24** [comment]
Hi @RekGRpth 

Thank you for the reproduction. I took your reproduction for a test run and saw that it produces errors in the `pxf-service.log`. While this does produce the partial transfer error, it is not quite the scenario that we are looking for. 

In this case, we hit a SQLException (due to `ERROR: division by zero` while running the query. As we have already committed a response and started streaming the data, PXF is expecting more incoming data. By hitting the SQL error, we try to throw an error response but are unable to as the response has already been committed. This interruption in the stream is what causes a partial transfer error as PXF was expecting data but received none. When you ran the query you provided in your reproduction, were there errors logged in the `pxf-service.log`? 

We are looking for a case when there is a partial transfer error but there are no errors in the pxf-service.log.

If you are willing, could you possibly open an issue with as much information as you can provide regarding the original partial file transfer error that you saw? Any information would be helpful: 
- What kind of query were you running when the error first occurred? Has it occurred since?
- How much data was being transferred, etc
- Were you running any concurrent queries? 
- Were there any errors in the pxf-service.log?

Thanks so much.

**Comment by RekGRpth** [comment]
We found another non-trivial reproduction of the problem on the demo cluster of 6X.
1) prepare data
```sql
create extension pxf;

CREATE TABLE source_table (id  integer, name text, body   text, type   varchar(1000), format varchar(1000), job_id integer);
CREATE TABLE dist_table (LIKE source_table);
CREATE TABLE etl_table (LIKE source_table);

insert into source_table values (1, 'name1', 'body1', 'type1', 'format1', 1);
insert into source_table values (2, 'name2', 'body2', 'type2', 'format2', 2);
insert into source_table values (3, 'name3', 'body3', 'type3', 'format2', 3);
insert into source_table values (4, 'name4', 'body4', 'type4', 'format4', 4);
insert into source_table values (5, 'name5', 'body5', 'type5', 'format5', 5);
insert into etl_table select * from source_table;

CREATE readable EXTERNAL TABLE ext_read_table (
id  integer, name text, body   text, type   varchar(1000), format varchar(1000), job_id integer
) LOCATION ('pxf://etl_table?PROFILE=JDBC&JDBC_DRIVER=org.postgresql.Driver&DB_URL=jdbc:postgresql://localhost:6432/postgres') 
FORMAT 'CUSTOM' (FORMATTER='pxfwritable_import');

CREATE WRITABLE EXTERNAL  TABLE ext_write_table (
id  integer, name text, body   text, type   varchar(1000), format varchar(1000), job_id integer
) LOCATION ('pxf://etl_table?PROFILE=JDBC&JDBC_DRIVER=org.postgresql.Driver&DB_URL=jdbc:postgresql://localhost:6432/postgres') 
FORMAT 'CUSTOM' (FORMATTER='pxfwritable_export');

insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;

insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
insert into etl_table select * from etl_table;
```
2) install pgbench
```sh
yum install -y postgresql-contrib-9.2.24
```
3) `stress_test.sql`
```sql
set log_min_messages = debug3; set optimizer = off; insert into ext_write_table select * from source_table limit 1;
set log_min_messages = debug3; set optimizer = off; insert into dist_table select * from ext_read_table limit 1;
```
4) catch error
```sh
tail -F */*/pg_log/*.csv | grep 'curl error buffer: transfer closed with outstanding read data remaining'
```
5) run `pgbench`
```sh
pgbench -d postgres -c 6 -j 6 -T 600 -f stress_test.sql -n
[pxf-seg2.log](https://github.com/greenplum-db/pxf/files/11538697/pxf-seg2.log)
[pxf-seg1.log](https://github.com/greenplum-db/pxf/files/11538698/pxf-seg1.log)
[pxf-seg0.log](https://github.com/greenplum-db/pxf/files/11538699/pxf-seg0.log)
[gp-seg2.log](https://github.com/greenplum-db/pxf/files/11538700/gp-seg2.log)
[gp-seg1.log](https://github.com/greenplum-db/pxf/files/11538701/gp-seg1.log)
[gp-seg0.log](https://github.com/greenplum-db/pxf/files/11538702/gp-seg0.log)
[gp-seg-1.log](https://github.com/greenplum-db/pxf/files/11538703/gp-seg-1.log)

```

**Pull request merged**
